pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/shahidafrid366/lmsnode20.git', branch: 'main'
            }
        }
    }
      post {
        always {
            echo 'Pipeline execution completed.'
        }
    }
}
