pipeline {
    agent any
    environment {
        SONARQUBE_SCANNER_HOME = tool name: 'SonarQubeScanner', type: 'SonarQubeScanner'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/shahidafrid366/lmsnode20.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
               sh 'npm install && npm run build'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'sonar-scanner -Dsonar.projectKey=react-app -Dsonar.sources=react-app/src'
                }
            }
        }
    }
      post {
        always {
            echo 'Pipeline execution completed.'
        }
    }
}
